// Recovery regressions exercise the real desktop state machine and controlled browser promises.
import assert from 'node:assert/strict'
import test from 'node:test'
import { deferred, flush, harness, item, playable } from './helpers/player-harness.mjs'

test('a queued pause event after resume does not stop the new progress watchdog', async () => {
  const h = harness()
  h.player.playQueue([item()], 0)
  await flush()
  const a = h.audios.at(-1)
  h.player.toggle()
  h.player.toggle()
  await flush()
  assert.equal(a.paused, false)
  a.dispatchEvent(new Event('pause'))
  assert.equal(h.player.status, 'playing')
  await h.advance(30_000)
  assert.deepEqual(h.resolutions.filter(([, refresh]) => refresh), [[1, true]])
})

test('a browser-originated pause remains resumable without toggling pause a second time', async () => {
  const h = harness()
  h.player.playQueue([item()], 0)
  await flush()
  h.audios.at(-1).pause()
  assert.equal(h.player.status, 'paused')
  h.player.toggle()
  await flush()
  assert.equal(h.player.status, 'playing')
})

function start(audio) {
  audio.paused = false
  audio.dispatchEvent(new Event('playing'))
  return Promise.resolve()
}
function progress(audio, at) {
  audio.currentTime = at
  audio.dispatchEvent(new Event('timeupdate'))
}

test('a silent stall rebuilds the current local decoder once, preserving position and history', async () => {
  const h = harness({ resolve: async () => ({ url: 'http://127.0.0.1:32123/token/file', local: true }) })
  h.player.playQueue([item(1), item(2)], 0)
  await flush()
  const original = h.audios.at(-1)
  progress(original, 47)
  const resolutionsBefore = [...h.resolutions]
  await h.advance(30_000)
  const repaired = h.audios.at(-1)
  assert.notEqual(repaired, original)
  assert.equal(original.src, '')
  assert.equal(repaired.currentTime, 47)
  assert.equal(h.player.current.track.id, 1)
  assert.equal(h.player.time, 47)
  assert.deepEqual(h.sources, ['http://127.0.0.1:32123/token/file', 'http://127.0.0.1:32123/token/file'])
  assert.deepEqual(h.resolutions, resolutionsBefore, 'local decoder repair must not ask any extractor')
  progress(repaired, 48)
  assert.deepEqual(h.records, [1], 'repair is the same listening session')
  await h.advance(30_000)
  assert.equal(h.player.status, 'idle')
  assert.equal(h.player.current.track.id, 1, 'a persistent stall must not skip the queue')
  assert.equal(h.player.time, 48)
  assert.equal(h.messages.length, 1)
  assert.equal(h.timers.size, 0)
  h.player.toggle()
  await flush()
  assert.equal(h.player.status, 'playing')
  assert.equal(h.audios.at(-1).currentTime, 48)
  progress(h.audios.at(-1), 49)
  assert.deepEqual(h.records, [1])
})

test('a silent remote stall renews the same track and retains the manual queue position', async () => {
  const h = harness({ resolve: async (track, refresh) => playable(track.id + (refresh ? 1000 : 0)) })
  h.player.playQueue([item(1), item(2)], 0)
  await flush()
  h.player.addToQueue([item(90), item(91)])
  h.player.next()
  await flush()
  progress(h.audios.at(-1), 87)
  await h.advance(30_000)
  assert.equal(h.player.current.track.id, 90)
  assert.equal(h.player.time, 87)
  assert.equal(h.audios.at(-1).currentTime, 87)
  assert.deepEqual(h.resolutions.filter(([, refresh]) => refresh), [[90, true]])
  assert.deepEqual(h.player.userQueue.map(({ item }) => item.track.id), [91])
  h.audios.at(-1).dispatchEvent(new Event('ended'))
  await flush()
  assert.equal(h.player.current.track.id, 91)
  h.audios.at(-1).dispatchEvent(new Event('ended'))
  await flush()
  assert.equal(h.player.current.track.id, 2)
})

test('pause during stall renewal cancels autoplay even when the renewed source arrives later', async () => {
  const renewal = deferred()
  const h = harness({ resolve: (track, refresh) => refresh ? renewal.promise : Promise.resolve(playable(track.id)) })
  h.player.playQueue([item(1), item(2)], 0)
  await flush()
  progress(h.audios.at(-1), 62)
  await h.advance(30_000)
  assert.equal(h.player.status, 'loading')
  h.player.toggle()
  assert.equal(h.player.status, 'paused')
  renewal.resolve(playable(1001))
  await flush()
  assert.equal(h.player.status, 'paused')
  assert.equal(h.player.time, 62)
  assert.deepEqual(h.sources, ['https://audio.test/1'])
  await h.advance(180_000)
  assert.equal(h.player.status, 'paused')
  assert.equal(h.messages.length, 0)
  h.player.toggle()
  await flush()
  assert.equal(h.player.current.track.id, 1)
  assert.equal(h.audios.at(-1).currentTime, 62)
  assert.equal(h.player.status, 'playing')
})

test('pausing a pending resume ignores its late playing event and rejected promise', async () => {
  const pending = deferred()
  let attempts = 0
  const h = harness({ play: (audio) => ++attempts === 1 ? start(audio) : pending.promise })
  h.player.playQueue([item()], 0)
  await flush()
  const audio = h.audios.at(-1)
  progress(audio, 35)
  h.player.toggle()
  h.player.toggle()
  assert.equal(h.player.status, 'loading')
  h.player.toggle()
  assert.equal(h.player.status, 'paused')
  audio.paused = false
  audio.dispatchEvent(new Event('playing'))
  assert.equal(audio.paused, true)
  pending.reject(new DOMException('Cancelled play', 'AbortError'))
  await flush()
  await h.advance(180_000)
  assert.equal(h.player.status, 'paused')
  assert.equal(h.player.time, 35)
  assert.equal(h.messages.length, 0)
  assert.equal(h.timers.size, 0)
})

test('pause during initial resolution keeps the loaded queue without starting the late URL', async () => {
  const pending = deferred()
  const h = harness({ resolve: () => pending.promise })
  h.player.playQueue([item()], 0)
  h.player.toggle()
  pending.resolve(playable())
  await flush()
  assert.equal(h.player.status, 'paused')
  assert.equal(h.player.current.track.id, 1)
  assert.deepEqual(h.sources, [])
  h.player.toggle()
  await flush()
  assert.equal(h.player.status, 'playing')
  assert.deepEqual(h.sources, ['https://audio.test/1'])
})

test('MediaSession play and pause commands are idempotent and preserve pause intent', async () => {
  const handlers = new Map()
  const h = harness({ mediaSession: { setActionHandler: (action, fn) => handlers.set(action, fn) } })
  h.player.playQueue([item()], 0)
  await flush()
  handlers.get('pause')()
  handlers.get('pause')()
  assert.equal(h.player.status, 'paused')
  handlers.get('play')()
  await flush()
  handlers.get('play')()
  assert.equal(h.player.status, 'playing')
  handlers.get('pause')()
  await h.advance(180_000)
  assert.equal(h.player.status, 'paused')
  assert.equal(h.messages.length, 0)
})

test('duplicate playing and stationary timeupdate events cannot postpone the watchdog', async () => {
  const h = harness()
  h.player.playQueue([item()], 0)
  await flush()
  const audio = h.audios.at(-1)
  progress(audio, 60)
  await h.advance(20_000)
  audio.dispatchEvent(new Event('playing'))
  progress(audio, 60)
  await h.advance(9_999)
  assert.equal(h.resolutions.filter(([, refresh]) => refresh).length, 0)
  audio.dispatchEvent(new Event('playing'))
  await h.advance(1)
  assert.deepEqual(h.resolutions.filter(([, refresh]) => refresh), [[1, true]])
})

test('a backwards seek resets the watchdog baseline and ongoing progress avoids recovery', async () => {
  const h = harness()
  h.player.playQueue([item()], 0)
  await flush()
  const audio = h.audios.at(-1)
  progress(audio, 120)
  await h.advance(20_000)
  h.player.seek(10)
  for (const at of [20, 30, 40]) {
    await h.advance(20_000)
    progress(audio, at)
  }
  assert.equal(h.player.status, 'playing')
  assert.equal(h.audios.at(-1), audio)
  assert.deepEqual(h.resolutions, [[1, false]])
  assert.equal(h.messages.length, 0)
})

test('skip while stall renewal is pending discards its late errors and source', async () => {
  const renewal = deferred()
  const h = harness({ resolve: (track, refresh) => refresh ? renewal.promise : Promise.resolve(playable(track.id)) })
  h.player.playQueue([item(1), item(2)], 0)
  await flush()
  const old = h.audios.at(-1)
  progress(old, 40)
  await h.advance(30_000)
  h.player.next()
  await flush()
  renewal.resolve(playable(1001))
  old.fail(4)
  old.dispatchEvent(new Event('ended'))
  await flush()
  assert.equal(h.player.current.track.id, 2)
  assert.equal(h.player.status, 'playing')
  assert.ok(!h.sources.includes('https://audio.test/1001'))
  assert.equal(h.messages.length, 0)
})

test('remote errors while paused do not start playback, and explicit resume can refresh them', async () => {
  const h = harness({ resolve: async (_track, refresh) => playable(refresh ? 99 : 1) })
  h.player.playQueue([item()], 0)
  await flush()
  progress(h.audios.at(-1), 42)
  h.player.toggle()
  h.audios.at(-1).fail(4)
  await flush()
  assert.equal(h.player.status, 'paused')
  assert.deepEqual(h.resolutions, [[1, false]])
  h.player.toggle()
  await flush()
  assert.equal(h.player.status, 'playing')
  assert.equal(h.audios.at(-1).currentTime, 42)
  assert.deepEqual(h.resolutions, [[1, false], [1, true]])
})

test('a media error from the repaired decoder stops on the current track instead of skipping it', async () => {
  const h = harness({ resolve: async (track) => playable(track.id, true) })
  h.player.playQueue([item(1), item(2)], 0)
  await flush()
  progress(h.audios.at(-1), 42)
  await h.advance(30_000)
  h.audios.at(-1).fail(3)
  await flush()
  assert.equal(h.player.status, 'idle')
  assert.equal(h.player.current.track.id, 1)
  assert.equal(h.messages.length, 1)
})

for (const pending of [false, true]) {
  test('repeat-one restart is bounded when play ' + (pending ? 'hangs' : 'rejects'), async () => {
    let attempts = 0
    const h = harness({ play: (audio) => {
      if (++attempts === 1) return start(audio)
      return pending ? new Promise(() => {}) : Promise.reject(new Error('Decoder refused restart'))
    } })
    h.player.playQueue([item(1), item(2)], 0)
    await flush()
    h.player.repeat = 'one'
    h.audios.at(-1).dispatchEvent(new Event('ended'))
    await h.advance(30_000)
    assert.equal(h.player.status, 'idle')
    assert.equal(h.player.current.track.id, 1)
    assert.equal(h.messages.length, 1)
    assert.equal(h.timers.size, 0)
  })
}
